[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  " neocompleteの設定
  let g:neocomplete#enable_at_startup = 1
  " ポップアップメニューで表示される候補の数
  let g:neocomplete#max_list = 50
  " キーワードの長さ
  "let g:neocomplete#max_keyword_
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " 【C-e】NERDTreeを起動
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  " ステータスラインのカラースキーム変更
  let g:lightline = {
    \ 'colorscheme': 'wombat'
    \ }
'''

